transport_negative:
  name: 'Transports - negative'
  category: 'Transports'
  sub_categories:
    - sub_category:
      title: 'Transports'
      option: 'Vieglie auto'
    - sub_category:
      title: 'Vieglie auto'
      option: 'Audi'
    - sub_category:
      title: 'Audi'
      option: 'Audi A4'
    - sub_category:
      title: 'Darb카ba'
      option: 'P훮rdod'
  parameters: []

transport_positive:
  name: 'Transports - positive'
  category: 'Transports'
  sub_categories:
    - sub_category:
      title: 'Transports'
      option: 'Vieglie auto'
    - sub_category:
      title: 'Vieglie auto'
      option: 'Audi'
    - sub_category:
      title: 'Audi'
      option: 'Audi A4'
    - sub_category:
      title: 'Darb카ba'
      option: 'P훮rdod'
  parameters:
    - parameter:
      name: 'NOSAUKUMS'
      left: 'labs'
      right: ''
    - parameter:
      name: 'CENA (EUR)'
      left: '1'
      right: '1000'